services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379"  # 使用隨機埠號避免衝突
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning --maxmemory 64mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M

  zen-mcp:
    build: .
    image: zen-mcp-server:latest
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - CUSTOM_MODELS_CONFIG_PATH=${CUSTOM_MODELS_CONFIG_PATH:-}
      - CUSTOM_API_URL=${CUSTOM_API_URL:-}
      - CUSTOM_API_KEY=${CUSTOM_API_KEY:-}
      - CUSTOM_MODEL_NAME=${CUSTOM_MODEL_NAME:-llama3.2}
      - DEFAULT_MODEL=${DEFAULT_MODEL:-auto}
      - DEFAULT_THINKING_MODE_THINKDEEP=${DEFAULT_THINKING_MODE_THINKDEEP:-high}
      - CONVERSATION_TIMEOUT_HOURS=${CONVERSATION_TIMEOUT_HOURS:-3}
      - MAX_CONVERSATION_TURNS=${MAX_CONVERSATION_TURNS:-20}
      - OPENAI_ALLOWED_MODELS=${OPENAI_ALLOWED_MODELS:-}
      - GOOGLE_ALLOWED_MODELS=${GOOGLE_ALLOWED_MODELS:-}
      - LOCALE=${LOCALE:-}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - WORKSPACE_ROOT=${WORKSPACE_ROOT:-${HOME}}
      - USER_HOME=${USER_HOME:-${HOME:-${USERPROFILE:-/root}}}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
      - PYTHONUNBUFFERED=1
    volumes:
      - ${WORKSPACE_ROOT:-.}:/workspace:ro
      - mcp_logs:/tmp
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true
    tty: true
    entrypoint: ["python"]
    command: ["server.py"]

  log-monitor:
    build: .
    image: zen-mcp-server:latest
    restart: unless-stopped
    depends_on:
      - zen-mcp
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - mcp_logs:/tmp
      - /etc/localtime:/etc/localtime:ro
    entrypoint: ["python"]
    command: ["log_monitor.py"]

volumes:
  redis_data:
  mcp_logs: